num2pydate
SciTools/cf-units pull request #172
Opened 2021-06-09 10:18 UTC by rcomer

## 🚀 Pull Request

Hopefully a simple one!

### Description

This PR exposes `cftime`'s `only_use_python_datetimes` keyword in our `num2date` function and method.  Also adds a convenience `num2pydate` function and method following [cftime's num2pydate](https://unidata.github.io/cftime/api.html#cftime.num2pydate).  This should make life easier for users who work exclusively with the standard calendar.

I couldn't find any existing tests for the `num2date` utility function, so added a new module.  I've kept the new tests pretty minimal as they are really just checking that the args have been passed correctly to the next function down.

2021-06-09 10:47 UTC, rcomer commented
I'd like to get this into v3 if possible, since users who might want it will likely have to update their `num2date` calls at v3 anyway.

2021-06-21 15:13 UTC, trexfeathers requested changes
Great idea @rcomer, just a tiny change for you...

2021-06-21 15:13 UTC, trexfeathers commented on doc/source/utilities.rst
> +.. autofunction:: num2pydate
Don't forget [`__all__` in `__init__.py`](https://github.com/rcomer/cf-units/blob/1f502c9635608afcdb1f4109484176c92026a4d6/cf_units/__init__.py#L49).

2021-06-21 15:33 UTC, trexfeathers commented
The pre-commit.ci failure is expected since I've activated it for this repo but the config file is still waiting in another PR.

2021-06-21 15:34 UTC, rcomer commented
Thanks @trexfeathers, I have made that change and also updated the license headers on the new test modules to the new style.  I assume the pre-commit failure just means I need to rebase again once #179 is merged?

2021-06-22 09:28 UTC, trexfeathers commented
OK @rcomer, I promise to not make any more conflicting changes to the code base. If you can rebase one last time, this is the next PR to go in!

2021-06-22 09:47 UTC, rcomer commented
Thanks @trexfeathers!  I have now rebased, blackened my changes and fixed some offending imports that were in the wrong order.

2021-06-22 09:49 UTC, trexfeathers approved these changes

2021-06-22 09:49 UTC, merged