Linting
SciTools/cf-units pull request #179
Opened 2021-06-21 11:32 UTC by trexfeathers

## 🚀 Pull Request

### Description

Closes #171.

Adds the 'standard' SciTools linters, and tidies some other small things.

2021-06-21 11:43 UTC, trexfeathers commented
The coverage reduction I think is to be expected, given the lines that Black tends to add. Depending on the reviewer's preference, I am happy for us to:

a. Temporarily alter the coverage settings to be tolerant of this shift.
b. Merge with a CI failure.

Let me know 🙂

2021-06-21 12:38 UTC, bjlittle commented
@trexfeathers Since there might be a bit of fluctuation given that we're moving stuff around and linting et al, I'd suggest making the codecov regression suitably large to accommodate changes, then once the dust settles, bump it back to `0.5%`

2021-06-22 08:37 UTC, bjlittle requested changes
@trexfeathers Looking good... just a couple of comments to service :+1:

2021-06-22 08:37 UTC, bjlittle commented on .pre-commit-config.yaml
> +        args: [--config=./pyproject.toml, .]
@trexfeathers This `pre-commit` hook for `black` should now only perform a `--check`, see https://github.com/SciTools/iris/pull/4181

2021-06-22 08:37 UTC, bjlittle commented on .pre-commit-config.yaml
> +        args: ["--profile", "black", "--filter-files"]
@trexfeathers This `pre-commit` hook for `isort` should now only perform a `--check`, see https://github.com/SciTools/iris/pull/4181

2021-06-22 08:54 UTC, trexfeathers commented on .pre-commit-config.yaml
> +        args: [--config=./pyproject.toml, .]
7555e8ff47d418081c4f8846bea6745f7c271716

2021-06-22 08:54 UTC, trexfeathers commented on .pre-commit-config.yaml
> +        args: ["--profile", "black", "--filter-files"]
7555e8ff47d418081c4f8846bea6745f7c271716

2021-06-22 09:14 UTC, bjlittle approved these changes

2021-06-22 09:14 UTC, merged

2021-06-22 09:22 UTC, trexfeathers commented
Thanks @bjlittle !