infrastructure refresh
SciTools/cf-units pull request #214
Opened 2022-02-16 18:18 UTC by bjlittle

## 🚀 Pull Request

### Description
This PR shows some love to the `cf-units` infra-structure.

In a nutshell:
- replaces `cirrus-ci` with GHA
- adopts use of GH `dependabot`
- adopts the use of `tox`
- adopts the automated building of `conda-lock` explicit environment spec files
  - supports `linux`, `osx` and `windows` locks  
- retires the previous hand crafted PyPI `sdist` and `bdist` building/testing and replaces with the `cibuildwheel` GHA
- refreshes `readthedocs` to use `mamba` for faster building
- adopts the `setuptools-scm-git-archive` plugin
- uses the `oldest-supported-numpy` meta package
- fixes the tests to support `py310` (replaces/incorporates #207)
- introduces min pin of `py38`

Next steps would be to extend `ci-wheels` to build for `osx` and `windows`, and rationalise the GHA to use `composite` actions.

2022-03-04 10:34 UTC, trexfeathers commented
If no-one has looked at this by Monday I will carve out some time.

2022-03-11 19:15 UTC, ocefpaf submitted a review, later dismissed

2022-03-16 17:04 UTC, trexfeathers requested changes
That was a tough review!

Thanks for the effort @bjlittle - a big improvement. Got some comments for you.

(@bjlittle and I suspect that having `setuptools` in the dependencies YAML means that the other setup dependencies (specified in `pyproject.toml`) will all get picked up automatically. If not, we will find out when RTD fails!)

2022-03-16 17:04 UTC, trexfeathers commented on .github/workflows/ci-tests.yml
> +            post-command: codecov
The `codecov` command doesn't seem to be able to reach CodeCov - [see this run](https://github.com/SciTools/cf-units/runs/5284809124?check_suite_focus=true#step:10:519).

2022-03-16 17:04 UTC, trexfeathers commented on tox.ini
> +    conda-lock --channel conda-forge --file {env:TMPFILE} --platform linux-64 --filename-template "{envname}-\{platform\}.txt" {posargs}
This currently falls over. We are experiencing similar issues everywhere we run conda-lock. I can't provide my traceback as it includes proprietary information, but I expect the latest on our investigation can be found here: SciTools/iris#4638.

2022-03-16 17:04 UTC, trexfeathers commented on pyproject.toml
> +target-version = ["py38", "py39"]
```suggestion
target-version = ["py38", "py39", "py310"]
```

Unless there's a reason this was omitted here?

2022-03-16 17:04 UTC, trexfeathers commented on setup.cfg
> +    pytest>=6.0
This pin isn't reflected elsewhere. What's it for? Should it be included against other mentions of `pytest`?

2022-03-16 17:04 UTC, trexfeathers commented on tox.ini
> +    python -c 'from sys import version_info as v; fh = open("{env:TMPFILE}", "a"); fh.write(f"\n  - python =\{v.major\}.\{v.minor\}\n")'
Much neater than maintaining multiple identical YAML files 😎

2022-03-16 17:04 UTC, trexfeathers commented on .pre-commit-config.yaml
> +    )
Couldn't you just replace this with a global `types: [file, python]`?

[This seems to be encouraged by the pre-commit docs](https://[pre-commit](https://pre-commit.com/#filtering-files-with-types).com/#filtering-files-with-types):

>Filtering with `types` provides several advantages over traditional filtering with `files`.
>
> * no error-prone regular expressions
> * ...

And as far as I can tell this would achieve the same thing as the pattern you've written here, unless I've misunderstood the pattern?

And I suppose there might also be a deliberate reason you haven't used the `types` key for the Black item?

2022-03-16 17:04 UTC, trexfeathers commented on .github/workflows/actions/entrypoint.sh
> -#!/usr/bin/env bash
I have no experience with cf-units' advanced build process, so I'm relying on @ocefpaf's approval here 🙂

2022-03-16 17:04 UTC, trexfeathers commented on .github/workflows/actions/manylinux2014_x86_64/action.yml
> -name: 'build wheels with manylinux2014_x86_64'
I have no experience with cf-units' advanced build process, so I'm relying on @ocefpaf's approval here 🙂

2022-03-16 17:04 UTC, trexfeathers commented on .github/workflows/ci-wheels.yml
> +        path: ${{ github.workspace }}/wheelhouse/*.whl
I have no experience with cf-units' advanced build process, so I'm relying on @ocefpaf's approval here 🙂

2022-03-16 17:04 UTC, trexfeathers commented on pyproject.toml
> +  "setuptools_scm_git_archive",
I understand that this extra plugin is needed to make sure that `setuptools_scm` gets the right version information.

2022-03-16 17:04 UTC, trexfeathers commented on .github/workflows/ci-wheels.yml
> +on: [pull_request, push]
```suggestion
on:
  pull_request:

  push:
    branches-ignore:
      - "conda-lock-auto-update"
      - "pre-commit-ci-update-config"
      - "dependabot/*"
```

See bjlittle/geovista#50.

2022-03-16 17:04 UTC, trexfeathers commented on .github/workflows/ci-tests.yml
> +on: [pull_request, push]
```suggestion
on:
  pull_request:

  push:
    branches-ignore:
      - "conda-lock-auto-update"
      - "pre-commit-ci-update-config"
      - "dependabot/*"
```

See bjlittle/geovista#50.

2022-03-16 17:04 UTC, trexfeathers commented on .github/workflows/ci-locks.yml
> +          Conda lock files auto-updated to latest resolved environment for `cf-units` dependencies.
```suggestion
          Conda lock files auto-updated to latest resolved environment for `cf-units` dependencies.
          
          ### If the full suite of PR checks have not run, please close and re-open this pull request to trigger them.
```

See bjlittle/geovista#51.

2022-03-17 12:22 UTC, bjlittle commented on pyproject.toml
> +target-version = ["py38", "py39"]
As yet, it's not supported and including it causes an issue

2022-03-17 12:24 UTC, bjlittle commented on tox.ini
> +    python -c 'from sys import version_info as v; fh = open("{env:TMPFILE}", "a"); fh.write(f"\n  - python =\{v.major\}.\{v.minor\}\n")'
It's a *bit* of a hack, but I adopted this pattern on `geovista` as I did find it irksome having identical yaml files, apart from the `python` version for `iris`.

2022-03-17 12:25 UTC, bjlittle commented on tox.ini
> +    python -c 'from sys import version_info as v; fh = open("{env:TMPFILE}", "a"); fh.write(f"\n  - python =\{v.major\}.\{v.minor\}\n")'
@trexfeathers If we done the same on `iris`, would this upset any assumptions that you've built into the `asv` benchmarking proces?

2022-03-17 13:47 UTC, trexfeathers commented on tox.ini
> +    python -c 'from sys import version_info as v; fh = open("{env:TMPFILE}", "a"); fh.write(f"\n  - python =\{v.major\}.\{v.minor\}\n")'
> @trexfeathers If we done the same on `iris`, would this upset any assumptions that you've built into the `asv` benchmarking proces?

It'll probably be fine. Environment management is [this block](https://github.com/SciTools/iris/blob/b141b01b754fb0f012a0b4ffc812d66a3ca4c271/benchmarks/asv.conf.json#L21-L24) and [this block](https://github.com/SciTools/iris/blob/b141b01b754fb0f012a0b4ffc812d66a3ca4c271/noxfile.py#L361-L375). Looking at those, switching to Tox wouldn't exactly be a find-and-replace job, but we'd just need an easy way of instructing Tox to build an environment for **only the latest** Python.

2022-03-17 13:50 UTC, trexfeathers commented on pyproject.toml
> +target-version = ["py38", "py39"]
In that case it's rather odd that we're testing against Python `v3.10` - easy to misunderstand. Please could we either:

* Remove other references to `v3.10`?
  OR
* Stick an explanatory note here?

2022-03-17 21:19 UTC, bjlittle commented on .github/workflows/ci-wheels.yml
> +        path: ${{ github.workspace }}/wheelhouse/*.whl
@trexfeathers It's pretty much equivalent to this existing line in [cf-units/.github/workflows/actions/entrypoint.sh](https://github.com/SciTools/cf-units/blob/main/.github/workflows/actions/entrypoint.sh#L37)

2022-03-17 21:27 UTC, bjlittle commented on pyproject.toml
> +target-version = ["py38", "py39"]
@trexfeathers You've got to love open-source development... `py310` is available now :rocket:

2022-03-17 21:32 UTC, bjlittle commented on setup.cfg
> +    pytest>=6.0
It was a min pin for the major release, but there's no special need... so I'll remove it :+1:

2022-03-17 22:27 UTC, bjlittle commented on .pre-commit-config.yaml
> +    )
TBH this was inherited from `iris`, and in that case we definitely wanted to use that pattern as we didn't want to check all `*.py` files.

As you point out, quite rightly, this doesn't apply for `cf-units` (as far as I can tell) so I remove it and see what behaviour we get.

Also, from what I can recall, the choice of pattern for `black` was due to the way that we were using it in CI... and again on reflection, that might not hold here... so let's remove it and see how it rolls

2022-03-17 22:33 UTC, bjlittle commented on tox.ini
> +    conda-lock --channel conda-forge --file {env:TMPFILE} --platform linux-64 --filename-template "{envname}-\{platform\}.txt" {posargs}
Added a fix, which is to opt for `--kind explicit`

2022-03-17 22:58 UTC, bjlittle commented on .github/workflows/ci-tests.yml
> +            post-command: codecov
hmmmm yeah... seen this on geovista, then once i merged it, it worked :neutral_face:

2022-03-17 22:59 UTC, bjlittle commented on .github/workflows/ci-tests.yml
> +            post-command: codecov
i've added the secret to explicitly point to codecov... so, try and see?

dunno

2022-03-18 08:07 UTC, bjlittle commented on .github/workflows/ci-wheels.yml
> +        path: ${{ github.workspace }}/wheelhouse/*.whl
@ocefpaf already added his approval to this pr 7 days ago...

2022-03-18 15:29 UTC, bjlittle commented on .pre-commit-config.yaml
> +    )
Seems fine to me 👍

2022-03-31 13:10 UTC, trexfeathers commented on .github/workflows/ci-tests.yml
> +            post-command: codecov
[Still no good](https://github.com/SciTools/cf-units/runs/5641443060?check_suite_focus=true#step:10:519).

>seen this on geovista, then once i merged it, it worked 😐

OK, I'll ignore this one then.

2022-03-31 13:19 UTC, trexfeathers approved these changes

2022-03-31 13:20 UTC, trexfeathers commented
Beautiful @bjlittle!

And the PR's not bad either 😁

2022-03-31 13:20 UTC, merged