Relicense from LGPL-3 to BSD-3
SciTools/cf-units pull request #331
Opened 2023-01-05 13:33 UTC by lbdreyer

All the code in this repo comes from contributors who have now either signed the new CLA or are employees of the Met Office.

The new CLA enables us to relicense to BSD-3.

This PR:
* adds a BSD-3 LICENSE file (to replace the old COPYING* files)
* Updates the pypi classifiers/metadata etc
* Updates the file license headers

2023-01-06 09:59 UTC, bjlittle commented
@lbdreyer Test failure to investigate, but not your doing... 🤔

2023-01-06 11:46 UTC, rcomer commented
I think that test failure is just a method that shouldn't start with "test".

2023-01-06 11:47 UTC, pp-mo requested changes
Think this is what was wrong.
Haven't really checked anything else yet, but I'm sure it's right in spirit.

2023-01-06 11:47 UTC, pp-mo commented on cf_units/tests/__init__.py
> +
I think, according to the license-headers test, this line should have a "#", not just blank.
```suggestion
#
```

2023-01-06 11:47 UTC, pp-mo commented on cf_units/tests/integration/test_num2date.py
> +# See LICENSE in the root of the repository for full licensi
Bit went missing here.
```suggestion
# See LICENSE in the root of the repository for full licensing details.
```

2023-01-06 15:21 UTC, lbdreyer commented
Thanks for catching the problem @pp-mo !


The changes should now be correct

2023-01-07 01:08 UTC, bjlittle approved these changes
👍

2023-01-11 12:30 UTC, pp-mo approved these changes
Re-reviewing this to approve.
But I can't understand why this is necessary, since it lists no unresolved conversations.
Seen this before, I think it is possibly a GitHub bug ??

2023-01-11 12:33 UTC, merged

2023-01-11 15:58 UTC, lbdreyer commented
Thanks @pp-mo !