Initial setup of QA pre-commit tools [cf-units]
SciTools/cf-units pull request #522
Opened 2024-11-15 13:07 UTC by ukmo-ccbunney

## 🚀 Pull Request

### Description
Added following pre-commit hooks:
  - Extra "default" hooks from pre-commit (trailing whitespace, etc)
  - MyPy
  - codespell
  - validate_pyproject
  - numpydoc

`sp-repo-review` was already setup for cf-units, but have updated the ignore list as various tests now pass.

`ruff` was enabled, but with only selected tests. Have enabled "all"  tests.

For all QA tools above, the results of any "auto-fixes" have been included in this repo, mainly fixes for:
  - trailing whitespace
  - missing newline at end of file
  - docstring reformatting
  - some code style linting from ruff

All other failing tests have been added to ignore lists. See separate issues:
   - #520 
   - #521
   - #462

2024-11-17 13:20 UTC, ukmo-ccbunney commented
@pp-mo I Have resolved the issues I was having with pre-commit.ci.
I managed to reproduce the pre-commit.ci behaviour on my personal laptop which gave me a chance to investigate the issue.

I have reinstated the `PY005` check ("has test folder") to the to `[tool.repo-review] ignore` list.

The MyPy behaviour was more difficult to debug. It turns out that adding files to the MyPy `exclude` list only stops them being passed as filenames to the MyPy call. However, these will **still** be checked if they are `import`ed from some other module that is being checked.

There is a flag that can be passed to stop this `--follow-imports=silent`, but this is not supported via `pyproject.toml`.
However, I've found it can be set using the following too MyPy section:
```
[[tool.mypy.overrides]]
module = [
        "cf_units/_udunits2_parser/parser.*",
        "cf_units/_udunits2_parser/_antlr4_runtime.*",
]
ignore_errors = true
```

The combination of the above fix the errors on my personal laptop and the pre-commit.ci service, so this is ready for review now.

I don't know why the behaviour is different on the MO VDIs though (pre-commit and hook version numbers are same!)

2024-11-18 12:20 UTC, pp-mo commented
> `--follow-imports=silent`, but this is not supported via `pyproject.toml`

I don't think turning this totally off is a good idea, anyway.
Your fix to exclude certain files seems better to me.

2024-11-19 12:28 UTC, pp-mo requested changes
Ok but a few nit-picky suggestions.

You should also create some PRs to track unfinished business.
Suggest one each for :
  * re-order pre-commit entries based on [updated tempate file](https://github.com/SciTools/.github/pull/29)  : (can do this one right now)
  * mypy
  * ruff
  * numpydocs-validation

2024-11-19 12:28 UTC, pp-mo commented on cf_units/_udunits2_parser/_antlr4_runtime/Recognizer.py
> +# need forward declaration
It's not appropriate to modify **anything** inside `cf_units._udunits_parser._antlr4_runtime` ,
since this code is all copied directly from another project.

Effectively this is generated code, derived from the action of [compile.py](https://github.com/SciTools/cf-units/blob/v3.3.0/cf_units/_udunits2_parser/compile.py).
In a more ideal world, this code wouldn't exist in this repo, and we'd have it as a importable dependency instead.
It's only included in the project repo for convenience, specifically to avoid an awkward dependency.
See [./_udunits2_parser/README.md#generating-the-parser-from-the-grammar](https://github.com/SciTools/cf-units/blob/v3.3.0/cf_units/_udunits2_parser/README.md#generating-the-parser-from-the-grammar) for the lowdown.

So, we need to exclude this from the relevant checks.
I _think_ you can just add a top-level [exclude](https://pre-commit.com/#top_level-exclude) control to `.pre-commit-config.yaml`.

2024-11-19 12:28 UTC, pp-mo commented on .pre-commit-config.yaml
> +ci:
For consistency with the "repo procedures" templates in the project, 
I think this should also have a reference line `# See https://pre-commit.ci/#configuration` in the initial comment lines section above.

2024-11-19 12:28 UTC, pp-mo commented on .pre-commit-config.yaml
> +        # Check TOML file syntax.
It could be useful to feed these explainers back to the template, with a PR to [the 'template' file in to SciTools/.github](https://github.com/SciTools/.github/blob/6cd87da89ae606ccb4ce0a4c95421c012cb29108/templates/.pre-commit-config.yaml)

2024-11-19 12:28 UTC, pp-mo commented on pyproject.toml
> +#ignore-words-list = "Wirth"
What is this bit, can we either remove or explain ?

2024-11-19 12:28 UTC, pp-mo commented on pyproject.toml
> +    # NOTE: Non-permanent exclusions should be added to the ".ruff.toml" file.
Sorry to hit you with this, but I think the sprint team has now definitely decided **_not_** to do this. 
So, should remove this : the approach at [line 145](https://github.com/SciTools/cf-units/blob/7e9a9bb34bbcc3219391682cf12e7cebaf16dadd/pyproject.toml#L145) is now the way !

2024-11-19 12:28 UTC, pp-mo commented on pyproject.toml
> +    "PP003",  # Does not list wheel as a build-dep
FWIW I think it might be useful to keep these in alphabetical order.
Look like that is true of the existing, anyway

2024-11-19 12:28 UTC, pp-mo commented on pyproject.toml
> +    "D212",  # Multi-line docstring summary should start at the first line
The D212 entry appears to be redundant ?

2024-11-19 12:28 UTC, pp-mo commented on pyproject.toml
> +    "ALL",
It seems odd to me to have "exclude" followed by "select", since 'exclude' effectively qulaifies the 'select' choices.  
( but I've now raised this offline in our Teams sprint chat )

2024-11-19 13:01 UTC, ukmo-ccbunney commented on cf_units/_udunits2_parser/_antlr4_runtime/Recognizer.py
> +# need forward declaration
Rolled back changes to files in `_antlr4_runtime` directory and added top level exclusion in `pre-commit-config.yaml`; see 89afe5a

2024-11-19 13:03 UTC, ukmo-ccbunney commented on .pre-commit-config.yaml
> +ci:
Good spot; fixed in 2749787

2024-11-19 13:05 UTC, ukmo-ccbunney commented on pyproject.toml
> +#ignore-words-list = "Wirth"
Redundant exception - now removed; 843e6c2

2024-11-19 13:08 UTC, ukmo-ccbunney commented on pyproject.toml
> +    # NOTE: Non-permanent exclusions should be added to the ".ruff.toml" file.
Yep! Old comment. I've got nothing in .ruff.toml anyhow. Removed: 5a955ff

2024-11-19 13:19 UTC, ukmo-ccbunney commented on pyproject.toml
> +    "D212",  # Multi-line docstring summary should start at the first line
This was explicitly set in the standard scitools linter config (https://github.com/orgs/SciTools/projects/43/views/3?pane=issue&itemId=85886972), so I've left it in?

2024-11-19 13:22 UTC, ukmo-ccbunney commented on pyproject.toml
> +    "ALL",
Will raise a separate PR for this once we have a decision?

2024-11-19 13:27 UTC, ukmo-ccbunney commented on pyproject.toml
> +    "PP003",  # Does not list wheel as a build-dep
They were in order that repo-review reports them but it makes sense to alphabetise them for consistency; see 01fe1b7

2024-11-19 13:28 UTC, ukmo-ccbunney commented on .pre-commit-config.yaml
> +        # Check TOML file syntax.
I don't follow you here - the comments already exist in the template file.

2024-11-19 13:49 UTC, ukmo-ccbunney commented
> You should also create some PRs to track unfinished business. Suggest one each for :

I've already created Issues for these (not PRs), see links in description

> * re-order pre-commit entries based on [updated tempate file]

(https://github.com/SciTools/.github/pull/29)  : (can do this one right now)
Done; see d831bfb

2024-11-21 10:54 UTC, pp-mo commented on .pre-commit-config.yaml
> +        # Check TOML file syntax.
Oh I hadn't seen that !

2024-11-21 12:26 UTC, pp-mo commented on pyproject.toml
> +    "D212",  # Multi-line docstring summary should start at the first line
Yes, but I'm pretty sure it's wrong all the same.

To my frustration, they don't seem to actually document the "ALL" magic 😞 
But IIUC, the list of 'select' options is additive, so including "ALL" means anything else is redundant by definition.

(NB we have an ongoing offline teams convo about this)

2024-11-21 12:33 UTC, pp-mo requested changes
I think removing "D212" from the ruff.lint `select` is worth doing,
not least because the comment is confusing + I think wrong!

otherwise all looks great now + good to go !

2024-11-21 12:33 UTC, pp-mo commented on pyproject.toml
> +    "D212",  # Multi-line docstring summary should start at the first line
> they don't seem to actually document the "ALL" magic

Oh my mistake, it is there in the [command-line help](https://docs.astral.sh/ruff/configuration/#full-command-line-interface)

2024-11-21 12:46 UTC, ukmo-ccbunney commented on pyproject.toml
> +    "D212",  # Multi-line docstring summary should start at the first line
D212 removed from Ruff `select`; bb551e1
This resulted in a "unused NOQA" autofix on `__init__.py` which is also included in the commit.

2024-11-21 14:06 UTC, ukmo-ccbunney commented
Right - `D212` is back in the Ruff `select` list after `ALL`.
Hopefully this is everything that is needed now for this PR.

2024-11-21 15:06 UTC, pp-mo approved these changes

2024-11-21 15:06 UTC, merged